on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  external_info:
    runs-on: ubuntu-latest
    name: Get external info

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get all projects create during the Imers√£o React v3
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: CHANNEL_PROJECTS
        max_post_count: 100000
        feed_list: "https://github-feed-generator-theta.vercel.app/api/topic/aluracord/?v=10"
        template: "$newline| [<img width='500px' src='https://opengraph.githubassets.com/cf9f1db04b6e4e2b7a984902d69b889f717d09cb94b8b4296ffffc16d0c73120/$title'/>]($url)"
